Portfolio Desktop Version Pull Request
YoutLone/Portfolio pull request #4
Opened 2023-05-03 17:50 UTC by YoutLone

**### Portfolio Desktop Version**

- Add HTML and CSS for desktop version
- Add images  for design and background
- Add the links icon for the information

2023-05-03 20:18 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @YoutLone👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitHub Flow correctly 👍🏽
✅ Linter checks passed✔️
✅ Used Grid and Flexbox to lay out elements✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 20:18 UTC, Johnadibe commented on style.css
> -    padding-left: 20px;
> - [ ] Great job so far👍Please kindly ensure that you align your headline section to stick to the Figma design as much as possible. By following the Figma design closely, you can maintain consistency in your design and ensure that it aligns with the overall visual style of the project.☺
> 
> Figma design👇:
> 
> ![0-Z-figma](https://user-images.githubusercontent.com/40009354/236027585-4633b24a-c1a3-4ff5-9ddb-b0071b502fcc.png)
> 
> Your design👇:
> 
> ![0-Z](https://user-images.githubusercontent.com/40009354/236027705-8f0f6928-5566-40cd-b24c-68a7349e14d8.png)
> 
>

2023-05-03 20:18 UTC, Johnadibe commented on style.css
> +
> - [ ] While you did good work👍 I noticed that your paragraph overlaps with its container. Please kindly make sure it sticks to the Figma design as much as possible☺
> 
> Figma design👇:
> 
> ![0-Z1-figma](https://user-images.githubusercontent.com/40009354/236029969-cecd3eda-7d07-4d84-9a46-f1f9f1070e3f.png)
> 
> Your design👇:
> 
> ![0-Z1](https://user-images.githubusercontent.com/40009354/236030122-ad623a08-705e-4486-b799-2177b3a5b851.png)
>

2023-05-03 20:18 UTC, Johnadibe commented on style.css
> +  }
> - [ ] Good job here👍 I think it would be better if you adjust your paddings and margins to match with the Figma design as much as possible. By following the Figma design closely, you can maintain consistency in your design and ensure that it aligns with the overall visual style of the project.☺
> 
> Figma design👇:
> 
> ![0-Z2-figma](https://user-images.githubusercontent.com/40009354/236031520-6ed890fe-c02e-4f16-967a-c503a4061ef6.png)
> 
> Your design👇:
> 
> ![0-Z2](https://user-images.githubusercontent.com/40009354/236031664-96e551f9-7fe9-4520-81a5-a37b0afbfbd1.png)
>

2023-05-03 20:18 UTC, Johnadibe commented on style.css
> +
> - [ ] I suggest you adjust your margins to stick to the Figma design as much as possible. By following the Figma design closely, you can maintain consistency in your design and ensure that it aligns with the overall visual style of the project.☺
> 
> Figma design👇:
> 
> ![0-Z3-figma](https://user-images.githubusercontent.com/40009354/236035085-9e10161f-15f2-4577-a345-196488781e50.png)
> 
> Your design👇:
> 
> ![0-Z3](https://user-images.githubusercontent.com/40009354/236035250-5a33aa27-355b-4fd7-993a-40f368bb7442.png)
>

2023-05-03 20:18 UTC, Johnadibe commented on index.html
> +      </div>
> - [ ] Please kindly ensure you stick to the social-links color of the Figma design as much as possible.☺
> 
> Figma design👇:
> 
> ![0-Z4-figma](https://user-images.githubusercontent.com/40009354/236036312-670a8c25-d152-4b8c-a5af-968dc5331bab.png)
> 
> Your design👇:
> 
> ![0-Z4](https://user-images.githubusercontent.com/40009354/236036387-681299ea-b279-4eb0-b972-b4d3f779eca3.png)
>

2023-05-03 20:18 UTC, Johnadibe commented on style.css
> +}
> [OPTIONAL] I noticed that the .main-project-description does not stick to the Figma design on a mobile screen. Please kindly fix that👍
> 
> Figma design👇:
> 
> ![0-Z5-mobile-figma](https://user-images.githubusercontent.com/40009354/236038547-bde80878-3027-4847-9787-5d95316aea45.png)
> 
> Your design👇:
> 
> ![0-Z5-mobile](https://user-images.githubusercontent.com/40009354/236038684-fe2f9684-b413-4782-9a85-a7ee855098f5.png)
> 
>

2023-05-03 20:18 UTC, Johnadibe commented on index.html
> +          </div>
> - [ ] [OPTIONAL] I noticed that the project list section does not stick to the Figma design on a mobile screen. Please kindly fix that👍
> 
> Figma design👇:
> 
> ![0-Z6-mobile-figma](https://user-images.githubusercontent.com/40009354/236039875-432c620f-fb90-4300-bb3b-d6b04f434a60.png)
> 
> 
> Your design👇:
> 
> ![0-Z6-mobile](https://user-images.githubusercontent.com/40009354/236039939-af783ff6-2531-4cae-aec6-adada488e66e.png)
>

2023-05-04 06:09 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi @YoutLone, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing. 🤓
✅ Correct use of GitHub Flow.✅ Incorporates feedback from previous code reviews. 🎯
✅ Nice desktop design. 🙌

## Optional suggestions 💭

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-04 06:09 UTC, taldr27 commented on index.html
> +             </p>
- [ ] **[OPTIONAL]** Great job on incorporating the previous reviewer's suggestions! I just have a quick suggestion **to make your mobile view even more professional and user-friendly**. It seems like there's an issue with the layout on mobile devices where all the content is pushed to the left side and something strange is happening with your body. Would you mind taking a look at it? 🎯

  ### Here's a screenshot:
  ![image](https://user-images.githubusercontent.com/107952724/236124119-cf2077d7-78cd-4bf6-abe1-e778ab471818.png)

2023-05-04 06:23 UTC, merged